<?xml version="1.0" encoding="UTF-8"?><testrun name="WarehouseTest (3)" project="Lab4" tests="6" started="6" failures="1" errors="0" ignored="0">
  <testsuite name="com.jits.parcel.WarehouseTest" time="3.29">
    <testcase name="testToZip" classname="com.jits.parcel.WarehouseTest" time="1.307"/>
    <testcase name="testInvalidShippingType" classname="com.jits.parcel.WarehouseTest" time="0.416"/>
    <testcase name="testFromZip" classname="com.jits.parcel.WarehouseTest" time="0.405"/>
    <testcase name="testId" classname="com.jits.parcel.WarehouseTest" time="0.39"/>
    <testcase name="testNewParcelFromIncomingBarcode" classname="com.jits.parcel.WarehouseTest" time="0.388"/>
    <testcase name="getReport" classname="com.jits.parcel.WarehouseTest" time="0.384">
      <failure>
        <expected>89687676564	GRD 	Whse	DistCtr: DC1 Raleigh	Dest: 12 Main St. 30331
</expected>
        <actual>89687676564	GRD 	Whse 	DistCtr: DC1 Raleigh 	Dest: 12 Main St. 30331
</actual>org.junit.ComparisonFailure: expected:&lt;...9687676564	GRD 	Whse[	DistCtr: DC1 Raleigh]	Dest: 12 Main St. 3...&gt; but was:&lt;...9687676564	GRD 	Whse[ 	DistCtr: DC1 Raleigh ]	Dest: 12 Main St. 3...&gt;
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.jits.parcel.WarehouseTest.getReport(WarehouseTest.java:89)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.rules.ExpectedException$ExpectedExceptionStatement.evaluate(ExpectedException.java:239)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)

</failure>
    </testcase>
  </testsuite>
</testrun>
